version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "monthly"
  open-pull-requests-limit: 10
- package-ecosystem: "npm"
  open-pull-requests-limit: 10
  directory: "/"
  schedule:
    interval: "weekly"
  groups:
    dev:
      dependency-type: "development"
      # patterns:
      # - "@types/*"
      # - "types-*"
      # - "eslint*"
      # - "prettier*"
      # - "typescript*"
      # - "ts-node*"
      # - "ts-jest*"
      # - "jest*"
      # - "husky*"
      # - "lint-staged*"
      # - "commitlint*"
      # exclude-patterns:
      # - "rubocop*"
      update-types:
      - "minor"
      # - "patch"
    mui:
      dependency-type: "production"
      patterns:
      - "@mui*"
      - "@emotion*"
      update-types:
      - "minor"
      # - "patch"
    prod:
      dependency-type: "production"
      patterns:
      - "*"
      update-types:
      - "minor"
- package-ecosystem: pip
  directory: "/tempo/"
  schedule:
    interval: weekly
    time: "04:00"
  groups:
    dev:
      dependency-type: "development"
      # patterns:
      # - "black"
      # - "ruff"
      # - "watchfiles"
      update-types:
      - "minor"
    prod:
      dependency-type: "production"
      # patterns:
      # - "*"
      update-types:
      - "minor"
  open-pull-requests-limit: 10
