fragment UserDetails on User {
  ...UserBase
  metadata {
    key
    value
  }
  defaultShippingAddress {
    ...Address
  }
  defaultBillingAddress {
    ...Address
  }
  addresses {
    ...Address
  }
}
