import type { PageKlass } from '@tempo/api/auth/dist/apollo/types';
import * as richTextEditorFixtures from '@tempo/ui/components/inputs/RichTextEditor/fixtures.json';
import { AttributeInputType } from '@tempo/api/generated/constants';
import type { PageDetailsFragment, PageFragment } from '@tempo/api/generated/graphql';

const content = richTextEditorFixtures.richTextEditor;

export const pageList: PageFragment[] = [
  {
    __typename: 'Page',
    id: 'Jzx123sEt==',
    isPublished: true,
    slug: 'about',
    title: 'About',
  },
  {
    __typename: 'Page',
    id: 'Jzx123sEx==',
    isPublished: false,
    slug: 'about',
    title: 'About',
  },
  {
    __typename: 'Page',
    id: 'Jzx123sEu==',
    isPublished: true,
    slug: 'about',
    title: 'About',
  },
  {
    __typename: 'Page',
    id: 'Jzx123sEm==',
    isPublished: true,
    slug: 'about',
    title: 'About',
  },
];
export const page: PageDetailsFragment = {
  __typename: 'Page',
  attributes: [
    {
      attribute: {
        id: 'QXR0cmlidXRlOjI3',
        slug: 'author',
        name: 'Author',
        entityType: null,
        inputType: AttributeInputType.Dropdown,
        valueRequired: false,
        unit: null,
        choices: {
          __typename: 'ValueConnection',
          pageInfo: {
            __typename: 'PageInfo',
            endCursor: '',
            hasNextPage: false,
            hasPreviousPage: false,
            startCursor: '',
          },
          edges: [
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6ODc=',
                name: 'Suzanne Ellison',
                slug: 'suzanne-ellison',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6ODg=',
                name: 'Dennis Perkins',
                slug: 'dennis-perkins',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6ODk=',
                name: 'Dylan Lamb',
                slug: 'dylan-lamb',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
          ],
        },
        __typename: 'Attribute',
      },
      values: [
        {
          id: 'QXR0cmlidXRlVmFsdWU6ODk=',
          name: 'Dylan Lamb',
          slug: 'dylan-lamb',
          reference: null,
          __typename: 'Value',
          file: null,
          plainText: null,
          richText: null,
          boolean: null,
          date: null,
          dateTime: null,
          value: null,
        },
      ],
      __typename: 'Attribute',
    },
    {
      attribute: {
        id: 'QXR0cmlidXRlOjI5',
        slug: 'tag',
        name: 'Tag',
        entityType: null,
        inputType: AttributeInputType.Multiselect,
        valueRequired: false,
        unit: null,
        choices: {
          __typename: 'ValueConnection',
          pageInfo: {
            __typename: 'PageInfo',
            endCursor: '',
            hasNextPage: false,
            hasPreviousPage: false,
            startCursor: '',
          },
          edges: [
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTA=',
                name: 'Security',
                slug: 'security',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTE=',
                name: 'Support',
                slug: 'support',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTI=',
                name: 'Medical',
                slug: 'medical',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTM=',
                name: 'General',
                slug: 'general',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
          ],
        },
        __typename: 'Attribute',
      },
      values: [
        {
          id: 'QXR0cmlidXRlVmFsdWU6OTA=',
          name: 'Security',
          slug: 'security',
          reference: null,
          __typename: 'Value',
          file: null,
          plainText: null,
          richText: null,
          boolean: null,
          date: null,
          dateTime: null,
          value: null,
        },
      ],
      __typename: 'Attribute',
    },
  ],
  content: JSON.stringify(content),
  id: 'Kzx152sEm==',
  isPublished: false,
  metadata: [
    {
      __typename: 'MetadataItem',
      key: 'integration.id',
      value: '100023123',
    },
  ],
  pageKlass: {
    __typename: 'PageKlass',
    id: 'UGFnZVR5cGU6MQ==',
    name: 'Blog',
    attributes: [
      {
        id: 'QXR0cmlidXRlOjI3',
        name: 'Author',
        entityType: null,
        inputType: AttributeInputType.Dropdown,
        valueRequired: false,
        choices: {
          __typename: 'ValueConnection',
          pageInfo: {
            __typename: 'PageInfo',
            endCursor: '',
            hasNextPage: false,
            hasPreviousPage: false,
            startCursor: '',
          },
          edges: [
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6ODc=',
                name: 'Suzanne Ellison',
                slug: 'suzanne-ellison',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6ODg=',
                name: 'Dennis Perkins',
                slug: 'dennis-perkins',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6ODk=',
                name: 'Dylan Lamb',
                slug: 'dylan-lamb',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
          ],
        },
        __typename: 'Attribute',
      },
      {
        id: 'QXR0cmlidXRlOjI5',
        name: 'Tag',
        entityType: null,
        inputType: AttributeInputType.Multiselect,
        valueRequired: false,
        choices: {
          __typename: 'ValueConnection',
          pageInfo: {
            __typename: 'PageInfo',
            endCursor: '',
            hasNextPage: false,
            hasPreviousPage: false,
            startCursor: '',
          },
          edges: [
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTA=',
                name: 'Security',
                slug: 'security',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTE=',
                name: 'Support',
                slug: 'support',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTI=',
                name: 'Medical',
                slug: 'medical',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
            {
              __typename: 'ValueCountableEdge',
              cursor: '',
              node: {
                id: 'QXR0cmlidXRlVmFsdWU6OTM=',
                name: 'General',
                slug: 'general',
                reference: null,
                __typename: 'Value',
                file: null,
                plainText: null,
                richText: null,
                boolean: null,
                date: null,
                dateTime: null,
                value: null,
              },
            },
          ],
        },
        __typename: 'Attribute',
      },
    ],
  },
  privateMetadata: [],
  publishedAt: '',
  seoDescription: 'About',
  seoTitle: 'About',
  slug: 'about',
  title: 'About',
};

export const pageKlassesList: Array<Pick<PageKlass, 'id' | 'name'>> = [
  {
    id: '1111ZHVjdFR5cGU6Nw==',
    name: 'General',
  },
  {
    id: '2222ZHVjdFR5cGU6Nw==',
    name: 'Subpages',
  },
  {
    id: '3333ZHVjdFR5cGU6Nw==',
    name: 'Blog',
  },
];
