query Page($slug: String!) {
  page(slug: $slug) {
    id
    title
    translation {
      id
      title
      content
    }
    seoTitle
    seoDescription
    slug
    createdAt
    content
  }
}
