services:
  storefront:
    container_name: kwstriping
    build:
      context: ..
      dockerfile: apps/Dockerfile
      args:
        - APP=kwstriping
    ports:
      - 3000:3000
    command: sh -c 'pnpm turbo run start --filter=storefront...'
