import type {
  ProductKlassDetailsQuery,
  ProductKlassListQuery,
  ProductKlassQuery,
  SearchProductKlassesQuery,
} from '@tempo/api/generated/graphql';
import { AttributeInputType, AttributeType } from '@tempo/api/generated/graphql';
import { WeightUnit, ProductKlassKind } from '@tempo/api/generated/constants';
import type { RelayToFlat } from '@tempo/dashboard/oldSrc/types';

export const attributes: ProductKlassQuery['productKlass']['productAttributes'] = [
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTo5',
      inputType: AttributeInputType.Dropdown,
      name: 'Author',
      slug: 'author',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjI0',
              name: 'John Doe',
              reference: null,
              slug: 'john-doe',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjI1',
              name: 'Milionare Pirate',
              reference: null,
              slug: 'milionare-pirate',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTo2',
      inputType: AttributeInputType.Dropdown,
      name: 'Box Size',
      slug: 'box-size',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE1',
              name: '100g',
              reference: null,
              slug: '100g',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE2',
              name: '250g',
              reference: null,
              slug: '250g',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE3',
              name: '500g',
              reference: null,
              slug: '500g',
              sortOrder: 2,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE4',
              name: '1kg',
              reference: null,
              slug: '1kg',
              sortOrder: 3,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZToz',
      inputType: AttributeInputType.Dropdown,
      name: 'Brand',
      slug: 'brand',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjY=',
              name: 'Tempo',
              reference: null,
              slug: 'tempo',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTo4',
      inputType: AttributeInputType.Dropdown,
      name: 'Candy Box Size',
      slug: 'candy-box-size',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjIx',
              name: '100g',
              reference: null,
              slug: '100g',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjIy',
              name: '250g',
              reference: null,
              slug: '250g',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjIz',
              name: '500g',
              reference: null,
              slug: '500g',
              sortOrder: 2,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTo1',
      inputType: AttributeInputType.Dropdown,
      name: 'Coffee Genre',
      slug: 'coffee-genre',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEz',
              name: 'Arabica',
              reference: null,
              slug: 'arabica',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE0',
              name: 'Robusta',
              reference: null,
              slug: 'robusta',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZToy',
      inputType: AttributeInputType.Dropdown,
      name: 'Collar',
      slug: 'collar',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjM=',
              name: 'Round',
              reference: null,
              slug: 'round',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjQ=',
              name: 'V-Neck',
              reference: null,
              slug: 'v-neck',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjU=',
              name: 'Polo',
              reference: null,
              slug: 'polo',
              sortOrder: 2,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTox',
      inputType: AttributeInputType.Dropdown,
      name: 'Color',
      slug: 'color',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE=',
              name: 'Blue',
              reference: null,
              slug: 'blue',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjI=',
              name: 'White',
              reference: null,
              slug: 'white',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZToxMg==',
      inputType: AttributeInputType.Dropdown,
      name: 'Cover',
      slug: 'cover',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjMw',
              name: 'Soft',
              reference: null,
              slug: 'soft',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjMx',
              name: 'Hard',
              reference: null,
              slug: 'hard',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjMy',
              name: 'Middle soft',
              reference: null,
              slug: 'middle-soft',
              sortOrder: 2,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjMz',
              name: 'Middle hard',
              reference: null,
              slug: 'middle-hard',
              sortOrder: 3,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjM0',
              name: 'Middle',
              reference: null,
              slug: 'middle',
              sortOrder: 4,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjM1',
              name: 'Very hard',
              reference: null,
              slug: 'very-hard',
              sortOrder: 5,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTo3',
      inputType: AttributeInputType.Dropdown,
      name: 'Flavor',
      slug: 'flavor',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjE5',
              name: 'Sour',
              reference: null,
              slug: 'sour',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjIw',
              name: 'Sweet',
              reference: null,
              slug: 'sweet',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZToxMQ==',
      inputType: AttributeInputType.Dropdown,
      name: 'Language',
      slug: 'language',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjI4',
              name: 'English',
              reference: null,
              slug: 'english',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjI5',
              name: 'Pirate',
              reference: null,
              slug: 'pirate',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZToxMA==',
      inputType: AttributeInputType.Dropdown,
      name: 'Publisher',
      slug: 'publisher',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjI2',
              name: 'Mirumee Press',
              reference: null,
              slug: 'mirumee-press',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjI3',
              name: 'Tempo Publishing',
              reference: null,
              slug: 'tempo-publishing',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
  {
    node: {
      __typename: 'Attribute' as const,
      entityType: null,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTo0',
      inputType: AttributeInputType.Dropdown,
      name: 'Size',
      slug: 'size',
      valueRequired: true,
      unit: null,
      choices: {
        __typename: 'ValueConnection' as const,
        pageInfo: {
          endCursor: 'WyI4IiwgIjMiXQ==',
          hasNextPage: false,
          hasPreviousPage: false,
          startCursor: 'WyIwIiwgIjQ5Il0=',
          __typename: 'PageInfo' as const,
        },
        edges: [
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjc=',
              name: 'XS',
              reference: null,
              slug: 'xs',
              sortOrder: 0,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjg=',
              name: 'S',
              reference: null,
              slug: 's',
              sortOrder: 1,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjk=',
              name: 'M',
              reference: null,
              slug: 'm',
              sortOrder: 2,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEw',
              name: 'L',
              reference: null,
              slug: 'l',
              sortOrder: 3,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEx',
              name: 'XL',
              reference: null,
              slug: 'xl',
              sortOrder: 4,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
          {
            __typename: 'ValueCountableEdge' as const,
            cursor: '',
            node: {
              __typename: 'Value' as const,
              file: null,
              id: 'UHJvZHVjdEF0dHJpYnV0ZVZhbHVlOjEy',
              name: 'XXL',
              reference: null,
              slug: 'xxl',
              sortOrder: 5,
              type: 'STRING',
              value: '',
              plainText: null,
              richText: null,
              boolean: null,
              date: null,
              dateTime: null,
            },
          },
        ],
      },
    },
  },
].map((edge) => edge.node);

export const productKlassSearch: ProductKlassQuery['productKlass'] = {
  __typename: 'ProductKlass' as const,
  hasVariants: true,
  id: 'UHJvZHVjdFR5cGU6NA==',
  name: 'Candy',
  productAttributes: [attributes[0]],
  taxClass: {
    __typename: 'TaxClass' as const,
    name: 'PB100000',
    id: 'Books / Manuals',
  },
};

export const productKlasses: Array<
  RelayToFlat<NonNullable<SearchProductKlassesQuery['search']>>[0] &
  ProductKlassListQuery['productKlasses']['edges'][0]['node']
> = [
  {
    __typename: 'ProductKlass' as const,
    hasVariants: true,
    id: 'UHJvZHVjdFR5cGU6NA==',
    isShippingRequired: true,
    name: 'Candy',
    kind: ProductKlassKind.Normal,
    productAttributes: [attributes[0]],
    taxClass: {
      __typename: 'TaxClass' as const,
      name: 'Shipping method',
      id: 'VGV4Q2xhc3M6MQ==',
    },
    variantAttributes: [attributes[1], attributes[2]],
  },
  {
    __typename: 'ProductKlass' as const,
    hasVariants: false,
    id: 'UHJvZHVjdFR5cGU6NQ==',
    isShippingRequired: false,
    name: 'E-books',
    kind: ProductKlassKind.Normal,
    productAttributes: [attributes[5]],
    taxClass: {
      __typename: 'TaxClass' as const,
      name: 'Digital goods',
      id: 'VGV4Q4xhc3M6MQ==',
    },
    variantAttributes: [attributes[0], attributes[3]],
  },
  {
    __typename: 'ProductKlass' as const,
    hasVariants: false,
    id: 'UHJvZHVjdFR5cGU6Mg==',
    isShippingRequired: true,
    name: 'Mugs',
    kind: ProductKlassKind.Normal,
    productAttributes: [attributes[7]],
    taxClass: {
      __typename: 'TaxClass' as const,
      name: 'Houseware',
      id: 'VGV4Q3xhc3M6MQ==',
    },
    variantAttributes: [attributes[2], attributes[5]],
  },
  {
    __typename: 'ProductKlass' as const,
    hasVariants: true,
    id: 'UHJvZHVjdFR5cGU6Mw==',
    isShippingRequired: true,
    name: 'Coffee',
    kind: ProductKlassKind.Normal,
    productAttributes: [attributes[8]],
    taxClass: {
      __typename: 'TaxClass' as const,
      name: 'PB100000',
      id: 'Books / Manuals',
    },
    variantAttributes: [attributes[1], attributes[4]],
  },
  {
    __typename: 'ProductKlass' as const,
    hasVariants: true,
    id: 'UHJvZHVjdFR5cGU6MQ==',
    isShippingRequired: true,
    name: 'T-Shirt',
    kind: ProductKlassKind.Normal,
    productAttributes: [attributes[4]],
    taxClass: {
      __typename: 'TaxClass' as const,
      name: 'PH403970',
      id: 'Wheelchair',
    },
    variantAttributes: [attributes[1], attributes[6]],
  },
].map((productKlass) => ({
  __typename: 'ProductKlass' as const,
  ...productKlass,
}));

export const productKlass: ProductKlassDetailsQuery['productKlass'] = {
  __typename: 'ProductKlass' as const,
  hasVariants: false,
  id: 'UHJvZHVjdFR5cGU6NQ==',
  isShippingRequired: false,
  metadata: [
    {
      __typename: 'MetadataItem',
      key: 'integration.id',
      value: '100023123',
    },
  ],
  name: 'E-books',
  kind: ProductKlassKind.Normal,
  privateMetadata: [],
  productAttributes: [
    {
      __typename: 'Attribute' as const,
      filterableInDashboard: true,
      filterableInStorefront: false,
      id: 'UHJvZHVjdEF0dHJpYnV0ZTo5',
      name: 'Author',
      slug: 'author',
      type: AttributeType.ProductKlass,
      inputType: AttributeInputType.Dropdown,
      visibleInStorefront: true,
      unit: null,
    },
    {
      __typename: 'Attribute' as const,
      filterableInDashboard: true,
      filterableInStorefront: false,
      id: 'UHJvZHVjdEF0dHJpYnV0ZToxMQ==',
      name: 'Language',
      slug: 'language',
      type: AttributeType.ProductKlass,
      inputType: AttributeInputType.Dropdown,
      visibleInStorefront: true,
      unit: null,
    },
    {
      __typename: 'Attribute' as const,
      filterableInDashboard: true,
      filterableInStorefront: false,
      id: 'UHJvZHVjdEF0dHJpYnV0ZToxMA==',
      name: 'Publisher',
      slug: 'publisher',
      type: AttributeType.ProductKlass,
      inputType: AttributeInputType.Dropdown,
      visibleInStorefront: true,
      unit: null,
    },
  ],
  taxClass: {
    __typename: 'TaxClass',
    name: 'Shipping method',
    id: 'VGV4Q2xhc3M6MQ==',
  },
  variantAttributes: [
    {
      ...attributes[1],
      filterableInDashboard: true,
      filterableInStorefront: false,
      type: AttributeType.ProductKlass,
      visibleInStorefront: true,
      unit: null,
    },
    {
      ...attributes[6],
      filterableInDashboard: true,
      filterableInStorefront: false,
      type: AttributeType.ProductKlass,
      visibleInStorefront: true,
      unit: null,
    },
  ],
  productVariantAttributeAssignments: [
    {
      __typename: 'AssignedProductAttribute' as const,
      attribute: {
        __typename: 'Attribute' as const,
        filterableInDashboard: true,
        filterableInStorefront: false,
        id: 'UHJvZHVjdEF0dHJpYnV0ATo5',
        name: 'Author',
        slug: 'author',
        type: AttributeType.ProductKlass,
        inputType: AttributeInputType.Dropdown,
        visibleInStorefront: true,
        unit: null,
      },
      variantSelection: true,
    },
  ],
  weight: {
    __typename: 'Weight',
    unit: WeightUnit.Kg,
    value: 7.82,
  },
};
